# Generated by Django 3.1.3 on 2020-12-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='UniversityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('email', models.EmailField(default='temp@univ.con', max_length=100)),
                ('uploads', models.CharField(default='-1', max_length=100)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('passcode', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'univsinfo',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(default='temp@user.com', max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('uploads', models.CharField(default='', max_length=100)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('passcode', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'usersinfo',
            },
        ),
    ]
