# Generated by Django 3.1.3 on 2020-12-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture2',
            field=models.FileField(default='', upload_to='../input/'),
        ),
    ]
