# Generated by Django 3.1.3 on 2020-12-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_usermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='uploads',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
