# Generated by Django 3.1.3 on 2020-12-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0003_usermodel_uploads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='uploads',
        ),
    ]
