# Generated by Django 3.1.3 on 2020-12-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0004_auto_20201207_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FileField(upload_to='uploads_cdn/'),
        ),
    ]
