# Generated by Django 3.1.3 on 2020-12-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0004_remove_usermodel_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(default='abcd@abc.com', max_length=100),
        ),
    ]
