# Generated by Django 3.1.3 on 2020-12-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0005_auto_20201207_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
