# Generated by Django 3.1.3 on 2020-12-03 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0005_usermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='uploads',
            field=models.CharField(default='', max_length=100),
        ),
    ]
