# Generated by Django 3.1.3 on 2020-12-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0006_usermodel_uploads'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('passcode', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usersinfo1',
            },
        ),
    ]
