# Generated by Django 3.1.3 on 2020-12-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0007_universitymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
