# Generated by Django 3.1.3 on 2020-12-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0008_usermodel_last_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniversityModel',
        ),
    ]
