# Generated by Django 3.1.3 on 2020-12-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0009_delete_universitymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='passcode',
            field=models.IntegerField(default=0),
        ),
    ]
